### ISSUE TITLE
process_name_regex cannot see all JVMs

### ISSUE THREAD

**Issue by cslee00** [DataDog/jmxfetch#101]
The process_name_regex construct, to enumerate & connect to JVMs using the AttachAPI, can only see JVMs running as the same user account; in the default install of the dd agent this is only the jmxfetch JVM itself, running as dd-agent user - other JVMs aren't visible.

Running jmxfetch as root allows visibility to all JVMs.

**Comment by yannmh** [comment]
Hi @cslee00,

Thanks for reporting it.

We are aware of this limitation. It was introduced with https://github.com/DataDog/dd-agent/pull/1619 in Datadog Agent `5.4.0` as we decided to run JMXFetch with `dd-agent` user instead of `root` for security concerns. Unfortunately there is not much we can do here without going through a regression and compromising the host security.

Yann

**Comment by Bryji** [comment]
You could mention this limitation in the documentation
