### ISSUE TITLE
What's the right way to tell jmxfetch to refresh its cached beans list?

### ISSUE THREAD

**Issue by stephenchu** [DataDog/jmxfetch#127]
I have jmxfetch to plug lots of metrics off of a Kafka jvm. Every one a while, for good reasons, I may have to restart my Kafka process. If the running jmxfetch process does a refresh beans while the restart is happening, the number of mbeans it detects is significantly lower than what a normal properly running Kafka process support, and for the next 10 mins the metrics that plug off from this small number of mbeans will cause my Datadog monitors to alert due to "No data" being submitted.

The question is, what is the right way to restart the jmxfetch process? It appears that it is in a supervisor managed set up. Some trial and error suggests that sending a `-HUP` signal to the jmxfetch jvm will cause the jmxfetch process to restart itself, thus refresh its bean list.

Is this documented somewhere on how I should do this? TIA.

**Comment by yannmh** [comment]
@stephenchu,

1. Restart the Datadog Agent or the JMXFetch process after Kafka restarts
  ```
  # Restart the Datadog Agent
  sudo service datadog-agent restart
  
  # Only restart JMXFetch via the supervisor
  sudo -u dd-agent /opt/datadog-agent/embedded/bin/python /opt/datadog-agent/bin/supervisorctl -c /etc/dd-agent/supervisor.conf restart datadog-agent:jmxfetch
  ```
2. Alternatively you could also mitigate the problem by decreasing the value of the `refresh_bean` period. As refreshing MBeans can be CPU costly, I'd be careful and not set it "too low".
  ```yaml
  - host: localhost
    port: 9999
    
    # Refresh MBeans every 2 minutes
    refresh_beans: 120
  ```


> Some trial and error suggests that sending a -HUP signal to the jmxfetch jvm will cause the jmxfetch process to restart itself, thus refresh its bean list.

I am surprised to hear that you had success with signals. JMXFetch does not have any handler set for the `HUP` signal: in fact, as the application can run on Windows, we avoid signal based code, and use name pipes to communicates between the Datadog Agent and JMXFetch. 
That being said, I just gave a try, and ... indeed it does restart the process 💥 .  That's one method than can be added to 1.


Please let me know if that helps.

**Comment by stephenchu** [comment]
It does help. Thank you.

**Comment by jclarysse** [comment]
Can you re-open this issue, please?
  
> 1. Restart the Datadog Agent or the JMXFetch process after Kafka restarts 
This workaround assumes to be aware of the Kafka restart event, and when it actually completes. We identified the same issue with MirrorMaker2 where the restart process might be less predictable, and significantly longer than Kafka to complete. When connection is restored, the fetcher just gets a subset of beans as MM2 is restarting and JMX is not fully initialized for all beans that MM2 exposes. Here is the log:
````
2025-04-09 07:53:32 UTC | JMX | DEBUG | HttpClient | with body: {"checks":{"failed_checks":{},"initialized_checks":{"kafka_mirrormaker":[{"instance_name":"kafka_mirrormaker-localhost-9999","metric_count":0,"service_check_count":0,"message":"Unable to instantiate or initialize instance localhost:9999. Is the target JMX Server or JVM running? Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: localhost; nested exception is: \n\tjava.net.ConnectException: Connection refused]","status":"ERROR"},{"instance_name":"kafka_mirrormaker-localhost-9999","metric_count":27,"service_check_count":0,"message":null,"status":"OK"}]}},"errors":0,"info":{"runtime_version":"21.0.6","version":"0.46.0"},"timestamp":1744185212545}
``` 

> 2. Alternatively you could also mitigate the problem by decreasing the value of the `refresh_bean` period. 
This workaround doesn't work.

The fix should be that the JMXFetch would not invalidate the cached beans when connection to JMX is broken. In case of connection error, the refresh interval is reset, which looks wrong: https://github.com/DataDog/jmxfetch/blob/master/src/main/java/org/datadog/jmxfetch/Instance.java#L751
The refresh gets called from `init`, which seems to be called from here: https://github.com/DataDog/jmxfetch/blob/master/src/main/java/org/datadog/jmxfetch/App.java#L510

Instead of wiping the beans cache, it should keep the beans sitting there until the next refresh interval comes.
