### ISSUE TITLE
JVM metrics not showing up until 10 minutes after service starts up

### ISSUE THREAD

**Issue by brentm5** [DataDog/jmxfetch#292]
We have have been trying to get custom metrics from resin to show up with the new jmxfetch feature in the APM agent.  We are able to get jvm metrics immediately however our resin metrics do not show up for ~ 10 minutes.

It appears that when the jmxfetch thread starts the resin process has not fully initialized so the resin beans are not available.  After 10 minutes the beans are refreshed and new ones added.  It appears we can get slightly around this by changing the interval to be shorter with the following options however this seems less than ideal. 

```
-Ddd.jmxfetch.refresh-beans-period=30
```

Is there anyway to delay the initial start of the jmx fetch process or double check in the beginning.  I am concerned that setting the beans refresh period to run more frequently could have performance implications.

**Comment by essobedo** [comment]
Fixed by https://github.com/DataDog/jmxfetch/pull/349 and https://github.com/DataDog/dd-trace-java/pull/2659

**Comment by olivielpeau** [comment]
Thanks @essobedo for updating this issue, this is indeed configurable in the Datadog Agent since v7.26.0/v6.26.0 (with the option `refresh_beans_initial` option documented [here](https://docs.datadoghq.com/integrations/java/?tab=host#configuration-options), and should be available in the Java APM client in v0.79.0.

Therefore I'll go ahead and close this issue.
